channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - anyio=3.5.0
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.0.5
  - attrs=22.1.0
  - backcall=0.2.0
  - beautifulsoup4=4.12.2
  - bleach=4.1.0
  - ca-certificates=2023.05.30
  - cffi=1.15.1
  - comm=0.1.2
  - debugpy=1.5.1
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - executing=0.8.3
  - icu=58.2
  - idna=3.4
  - importlib-metadata=6.0.0
  - importlib_metadata=6.0.0
  - ipykernel=6.19.2
  - ipython=8.12.0
  - ipython_genutils=0.2.0
  - jedi=0.18.1
  - jinja2=3.1.2
  - jsonschema=4.17.3
  - jupyter_client=8.1.0
  - jupyter_core=5.3.0
  - jupyter_events=0.6.3
  - jupyter_server=2.5.0
  - jupyter_server_terminals=0.4.4
  - jupyterlab_pygments=0.1.2
  - ld_impl_linux-64=2.38
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libsodium=1.0.18
  - libstdcxx-ng=11.2.0
  - libxml2=2.10.3
  - libxslt=1.1.37
  - lxml=4.9.2
  - matplotlib-inline=0.1.6
  - mistune=0.8.4
  - nbclassic=0.5.5
  - nbclient=0.5.13
  - nbconvert=6.5.4
  - nbformat=5.7.0
  - ncurses=6.4
  - nest-asyncio=1.5.6
  - notebook=6.5.4
  - notebook-shim=0.2.2
  - openssl=3.0.9
  - packaging=23.0
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=23.1.2
  - platformdirs=2.5.2
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.36
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.15.1
  - pyrsistent=0.18.0
  - python=3.9.17
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - python-json-logger=2.0.7
  - pyyaml=6.0
  - pyzmq=25.1.0
  - readline=8.2
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - send2trash=1.8.0
  - setuptools=67.8.0
  - six=1.16.0
  - sniffio=1.2.0
  - soupsieve=2.4
  - sqlite=3.41.2
  - stack_data=0.2.0
  - terminado=0.17.1
  - tinycss2=1.2.1
  - tk=8.6.12
  - tornado=6.2
  - traitlets=5.7.1
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=0.58.0
  - wheel=0.38.4
  - xz=5.4.2
  - yaml=0.2.5
  - zeromq=4.3.4
  - zipp=3.11.0
  - zlib=1.2.13
  - pip:
      - aiofiles==23.1.0
      - aiohttp==3.8.4
      - aiosignal==1.3.1
      - altair==5.0.1
      - antlr4-python3-runtime==4.9.3
      - appdirs==1.4.4
      - async-timeout==4.0.2
      - audiocraft==0.0.1
      - audioread==3.0.0
      - av==10.0.0
      - blis==0.7.9
      - boto3==1.28.5
      - botocore==1.31.9
      - catalogue==2.0.8
      - certifi==2023.5.7
      - charset-normalizer==3.2.0
      - click==8.1.5
      - cloudpickle==2.2.1
      - cmake==3.26.4
      - colorlog==6.7.0
      - confection==0.1.0
      - contourpy==1.1.0
      - cycler==0.11.0
      - cymem==2.0.7
      - cython==0.29.36
      - demucs==4.0.0
      - diffq==0.2.4
      - docopt==0.6.2
      - dora-search==0.1.12
      - einops==0.6.1
      - fastapi==0.100.0
      - ffmpy==0.3.0
      - filelock==3.12.2
      - flashy==0.0.2
      - fonttools==4.41.0
      - frozenlist==1.4.0
      - fsspec==2023.6.0
      - geographiclib==2.0
      - geopy==2.3.0
      - gradio==3.36.1
      - gradio-client==0.2.9
      - h11==0.14.0
      - httpcore==0.17.3
      - httpx==0.24.1
      - huggingface-hub==0.16.4
      - hydra-colorlog==1.2.0
      - hydra-core==1.3.2
      - importlib-resources==6.0.0
      - jmespath==1.0.1
      - joblib==1.3.1
      - julius==0.2.7
      - kiwisolver==1.4.4
      - lameenc==1.5.1
      - langcodes==3.3.0
      - lazy-loader==0.3
      - librosa==0.10.0.post2
      - linkify-it-py==2.0.2
      - lit==16.0.6
      - llvmlite==0.40.1
      - markdown-it-py==2.2.0
      - markupsafe==2.1.3
      - matplotlib==3.7.2
      - mdit-py-plugins==0.3.3
      - mdurl==0.1.2
      - mpmath==1.3.0
      - msgpack==1.0.5
      - multidict==6.0.4
      - murmurhash==1.0.9
      - mypy-extensions==1.0.0
      - networkx==3.1
      - num2words==0.5.12
      - numba==0.57.1
      - numpy==1.24.4
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cuda-cupti-cu11==11.7.101
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cudnn-cu11==8.5.0.96
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-curand-cu11==10.2.10.91
      - nvidia-cusolver-cu11==11.4.0.1
      - nvidia-cusparse-cu11==11.7.4.91
      - nvidia-nccl-cu11==2.14.3
      - nvidia-nvtx-cu11==11.7.91
      - omegaconf==2.3.0
      - openunmix==1.2.1
      - orjson==3.9.2
      - paho-mqtt==1.6.1
      - pandas==2.0.3
      - pathy==0.10.2
      - pillow==10.0.0
      - pooch==1.6.0
      - preshed==3.0.8
      - pydantic==1.10.11
      - pydub==0.25.1
      - pyparsing==3.0.9
      - pyre-extensions==0.0.29
      - python-dotenv==1.0.0
      - python-multipart==0.0.6
      - pytz==2023.3
      - regex==2023.6.3
      - requests==2.31.0
      - retrying==1.3.4
      - s3transfer==0.6.1
      - safetensors==0.3.1
      - scikit-learn==1.3.0
      - scipy==1.11.1
      - semantic-version==2.10.0
      - sentencepiece==0.1.99
      - smart-open==6.3.0
      - soundfile==0.12.1
      - soxr==0.3.5
      - spacy==3.5.2
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.4
      - srsly==2.4.6
      - starlette==0.27.0
      - submitit==1.4.5
      - sympy==1.12
      - thinc==8.1.10
      - threadpoolctl==3.2.0
      - tokenizers==0.13.3
      - toolz==0.12.0
      - torch==2.0.1
      - torchaudio==2.0.2
      - tqdm==4.65.0
      - transformers==4.31.0
      - treetable==0.2.5
      - triton==2.0.0
      - typer==0.7.0
      - typing-extensions==4.7.1
      - typing-inspect==0.9.0
      - tzdata==2023.3
      - uc-micro-py==1.0.2
      - urllib3==1.26.16
      - uvicorn==0.23.0
      - wasabi==1.1.2
      - websockets==11.0.3
      - xformers==0.0.20
      - yarl==1.9.2
